# Generated by Django 4.2.26 on 2025-11-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(help_text="A unique name for this page, e.g., 'Home Page', 'Product List Page'.", max_length=100, unique=True)),
                ('page_path', models.CharField(help_text="The exact path, e.g., '/', '/products/', '/blog/'.", max_length=255, unique=True)),
                ('meta_title', models.CharField(help_text='The title tag for the page (60 chars).', max_length=255)),
                ('meta_description', models.CharField(help_text='The meta description for the page (160 chars).', max_length=160)),
            ],
            options={
                'ordering': ['page_path'],
            },
        ),
    ]
