# Generated by Django 4.2.27 on 2025-12-22 09:46

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, help_text="A unique code for this category (e.g., 'NIKE').", max_length=50, null=True, unique=True)),
                ('description', tinymce.models.HTMLField(blank=True, help_text='Description text displayed on the product list page when this category is selected.', null=True)),
                ('page_title', models.CharField(blank=True, help_text='Custom title to display on the product list page (overrides the category name).', max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='CategoryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, help_text="A unique code for this group (e.g., 'BRANDS').", max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, db_index=True, help_text='Stock Keeping Unit', max_length=100, null=True, unique=True)),
                ('description_title', models.CharField(blank=True, default='Product Description', help_text='Header for the main description section.', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_promotion', models.BooleanField(default=False, help_text='Check if this product is currently on promotion (triggers promotional styling).')),
                ('promotion_rate', models.DecimalField(blank=True, decimal_places=2, help_text='The rate/percentage defined for this promotion.', max_digits=5, null=True)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, help_text='The customer-facing selling price.', max_digits=10, null=True)),
                ('profit_margin', models.DecimalField(blank=True, decimal_places=2, help_text='Profit margin percentage (e.g., 20.00 for 20%)', max_digits=5, null=True)),
                ('members_only', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False, help_text='If checked, this product will appear on the Home page (subject to user permissions).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='products', to='product.category')),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_in_products', to='images.mediaimage')),
                ('gallery_images', models.ManyToManyField(blank=True, related_name='product_galleries', to='images.mediaimage')),
                ('suppliers', models.ManyToManyField(blank=True, help_text='Suppliers who provide this product.', related_name='products', to='inventory.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='ProductContentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_sections', to='product.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CategoryContentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', tinymce.models.HTMLField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_sections', to='product.category')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='product.categorygroup'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'group')},
        ),
    ]
