# Generated by Django 4.2.26 on 2025-12-01 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_promotion',
            field=models.BooleanField(default=False, help_text='Check if this product is currently on promotion (triggers promotional styling).'),
        ),
    ]
