# Generated by Django 4.2.26 on 2025-12-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_is_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='promotion_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The rate/percentage defined for this promotion.', max_digits=5, null=True),
        ),
    ]
