# Generated by Django 4.2.28 on 2026-02-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='origin_country',
            field=models.CharField(blank=True, help_text="Country of origin for the product (e.g., 'Malaysia', 'Korea').", max_length=100, null=True),
        ),
    ]
