# Generated by Django 4.2.25 on 2025-11-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_selling_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='profit_margin',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Profit margin percentage (e.g., 20.00 for 20%)', max_digits=5, null=True),
        ),
    ]
