# Generated by Django 4.2.28 on 2026-02-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_origin_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['display_order', '-created_at']},
        ),
        migrations.AddField(
            model_name='product',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Order of display on the product list page (lowest number appears first).'),
        ),
    ]
