# Generated by Django 4.2.26 on 2025-11-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_profit_margin'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='If checked, this product will appear on the Home page (subject to user permissions).'),
        ),
    ]
