# Generated by Django 4.2.28 on 2026-02-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_options_product_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_best_seller',
            field=models.BooleanField(default=False, help_text='If checked, this product will be highlighted as a Best Seller.'),
        ),
    ]
