# Generated by Django 4.2.26 on 2025-11-26 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_title',
            field=models.CharField(blank=True, default='Product Description', help_text='Header for the main description section.', max_length=255),
        ),
        migrations.CreateModel(
            name='ProductContentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_sections', to='product.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
