# Generated by Django 4.2.26 on 2025-11-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_description_title_productcontentsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Description text displayed on the product list page when this category is selected.', null=True),
        ),
    ]
