# Generated by Django 4.2.26 on 2025-11-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='page_title',
            field=models.CharField(blank=True, help_text='Custom title to display on the product list page (overrides the category name).', max_length=255, null=True),
        ),
    ]
