# Generated by Django 4.2.26 on 2025-11-27 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_category_page_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryContentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_sections', to='product.category')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
