# Generated by Django 4.2.26 on 2025-11-28 07:46

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_categorycontentsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=tinymce.models.HTMLField(blank=True, help_text='Description text displayed on the product list page when this category is selected.', null=True),
        ),
        migrations.AlterField(
            model_name='categorycontentsection',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
