# Generated by Django 4.2.27 on 2026-01-13 06:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(help_text='A number for this batch, e.g., PO-123. Can be duplicated across different products/deliveries.', max_length=100)),
                ('quantity', models.PositiveIntegerField(help_text='The actual quantity received.')),
                ('received_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, help_text='Optional: Expiry date for this batch.', null=True)),
            ],
            options={
                'verbose_name_plural': 'Inventory Batches',
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_id', models.CharField(blank=True, help_text='Unique ID for the quotation (e.g., QTN-YYMM-XXXX). Auto-generated if left blank.', max_length=20, unique=True)),
                ('date_quoted', models.DateField()),
                ('transportation_cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Total transportation cost for this entire quotation.', max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('quoted_price', models.DecimalField(decimal_places=2, help_text='Price per single unit for this item', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(blank=True, help_text="A unique code for this supplier (e.g., 'SUP001').", max_length=50, null=True, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
