# Generated by Django 4.2.27 on 2026-01-13 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        ('product', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.quotation'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='inventory.supplier'),
        ),
        migrations.AddField(
            model_name='inventorybatch',
            name='invoice_item',
            field=models.ForeignKey(blank=True, help_text='The specific invoice item this batch fulfills.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_batches', to='sales.invoiceitem'),
        ),
        migrations.AddField(
            model_name='inventorybatch',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='product.product'),
        ),
        migrations.AddField(
            model_name='inventorybatch',
            name='quotation',
            field=models.ForeignKey(help_text='The quotation this batch is based on.', on_delete=django.db.models.deletion.CASCADE, to='inventory.quotation'),
        ),
        migrations.AddField(
            model_name='inventorybatch',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier'),
        ),
    ]
