# Generated by Django 4.2.29 on 2026-03-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_quotationitem_input_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationitem',
            name='quoted_price',
            field=models.DecimalField(decimal_places=2, help_text='Price per single unit in MYR', max_digits=10),
        ),
    ]
