# Generated by Django 5.2.14 on 2026-06-22 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_quotationitem_quantity_default'),
        ('product', '0013_product_display_order_zero_to_ninety_nine'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPriceMatrixEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_medication', models.CharField(help_text='Medication / product name as shown on the supplier price list.', max_length=255)),
                ('strength', models.CharField(blank=True, max_length=255)),
                ('form', models.CharField(blank=True, help_text='e.g. INJ', max_length=50)),
                ('size', models.CharField(blank=True, help_text='e.g. 1 mL', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('source_filename', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_price_matrix_entries', to='product.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_matrix_entries', to='inventory.supplier')),
            ],
            options={
                'verbose_name': 'Supplier price matrix entry',
                'verbose_name_plural': 'Supplier price matrix entries',
                'ordering': ['line_medication', 'strength', 'size'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPriceMatrixTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.PositiveIntegerField(default=1)),
                ('max_quantity', models.PositiveIntegerField(blank=True, help_text='Null means open-ended (e.g. 2000+).', null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='inventory.supplierpricematrixentry')),
            ],
            options={
                'ordering': ['min_quantity'],
            },
        ),
        migrations.AddConstraint(
            model_name='supplierpricematrixentry',
            constraint=models.UniqueConstraint(fields=('supplier', 'line_medication', 'strength', 'size'), name='uniq_supplier_matrix_line'),
        ),
        migrations.AddConstraint(
            model_name='supplierpricematrixtier',
            constraint=models.UniqueConstraint(fields=('entry', 'min_quantity'), name='uniq_matrix_entry_tier_min_qty'),
        ),
    ]
