# Generated by Django 4.2.29 on 2026-06-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_supplier_price_matrix'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpricematrixentry',
            name='price_currency',
            field=models.CharField(choices=[('MYR', 'MYR'), ('USD', 'USD'), ('EUR', 'EUR')], default='MYR', help_text='Currency of the uploaded price list (stored tiers are normalized to MYR).', max_length=3),
        ),
    ]
