# Generated by Django 4.2.29 on 2026-06-22 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_supplier_price_matrix_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPriceMatrixUploadRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_filename', models.CharField(blank=True, max_length=255)),
                ('price_currency', models.CharField(default='MYR', max_length=3)),
                ('tiers', models.JSONField(default=list, help_text='Tier prices (MYR) after this upload: [{min_quantity, max_quantity, unit_price}, …]')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_records', to='inventory.supplierpricematrixentry')),
            ],
            options={
                'verbose_name': 'Supplier price matrix upload record',
                'verbose_name_plural': 'Supplier price matrix upload records',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
