# Generated by Django 4.2.29 on 2026-06-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_supplier_price_matrix_upload_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpricematrixentry',
            name='conversion_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Exchange rate used on last upload (1 unit of price_currency → MYR).', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='supplierpricematrixuploadrecord',
            name='conversion_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Exchange rate used for this upload (1 unit of price_currency → MYR).', max_digits=10, null=True),
        ),
    ]
