# Generated by Django 4.2.29 on 2026-06-25 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_matrix_upload_record_effective_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorybatch',
            name='quotation',
            field=models.ForeignKey(blank=True, help_text='The quotation this batch is based on (optional when receiving directly from an invoice).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.quotation'),
        ),
    ]
