# Generated by Django 4.2.29 on 2026-06-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_inventorybatch_quotation_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorybatch',
            name='batch_number',
            field=models.CharField(blank=True, default='', help_text='Optional lot/batch identifier. Can be set later when splitting a receipt.', max_length=100),
        ),
    ]
