# Generated by Django 4.2.27 on 2025-12-22 09:46

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='A unique URL-friendly path. Leave blank to auto-generate from title.', max_length=255, unique=True)),
                ('content', tinymce.models.HTMLField(blank=True, null=True)),
                ('post_type', models.CharField(choices=[('NEWS', 'Latest News'), ('ANNOUNCEMENT', 'Announcement'), ('MARKET_INSIGHTS', 'Market Insights'), ('FAQ', 'FAQ / Help'), ('FOOTER_LINK', 'Footer Quick Link'), ('MAIN_MENU', 'Main Menu Link')], default='NEWS', help_text='Define where this content belongs (e.g., Sidebar News, Announcement banner, etc.)', max_length=20)),
                ('related_products_title', models.CharField(blank=True, default='Related Products', help_text="Title to display above the related products section (e.g., 'Recommended for You').", max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Control the display order (lower numbers appear first). Useful for Main Menu links.')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
