# Generated by Django 4.2.27 on 2025-12-22 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
        ('user', '0001_initial'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_in_posts', to='images.mediaimage'),
        ),
        migrations.AddField(
            model_name='post',
            name='gallery_images',
            field=models.ManyToManyField(blank=True, related_name='post_galleries', to='images.mediaimage'),
        ),
        migrations.AddField(
            model_name='post',
            name='related_products',
            field=models.ManyToManyField(blank=True, help_text='Select products to display as related items on this post.', related_name='related_posts', to='product.product'),
        ),
        migrations.AddField(
            model_name='post',
            name='user_groups',
            field=models.ManyToManyField(blank=True, help_text='Select groups to restrict this post to. Leave blank for a public post.', related_name='blog_posts', to='user.usergroup'),
        ),
    ]
