# Generated by Django 4.2.26 on 2025-11-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('NEWS', 'Latest News'), ('ANNOUNCEMENT', 'Announcement'), ('FAQ', 'FAQ / Help')], default='NEWS', help_text='Define where this content belongs (e.g., Sidebar News, Announcement banner, etc.)', max_length=20),
        ),
    ]
