# Generated by Django 4.2.26 on 2025-11-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('NEWS', 'Latest News'), ('ANNOUNCEMENT', 'Announcement'), ('FAQ', 'FAQ / Help'), ('FOOTER_LINK', 'Footer Quick Link')], default='NEWS', help_text='Define where this content belongs (e.g., Sidebar News, Announcement banner, etc.)', max_length=20),
        ),
    ]
