# Generated by Django 4.2.26 on 2025-12-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('NEWS', 'Latest News'), ('ANNOUNCEMENT', 'Announcement'), ('MARKET_INSIGHTS', 'Market Insights'), ('FAQ', 'FAQ / Help'), ('FOOTER_LINK', 'Footer Quick Link'), ('MAIN_MENU', 'Main Menu Link')], default='NEWS', help_text='Define where this content belongs (e.g., Sidebar News, Announcement banner, etc.)', max_length=20),
        ),
    ]
