# Generated by Django 4.2.26 on 2025-12-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_post_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AddField(
            model_name='post',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Control the display order (lower numbers appear first). Useful for Main Menu links.'),
        ),
    ]
