# Generated by Django 4.2.26 on 2025-11-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_is_featured'),
        ('blog', '0005_alter_post_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='related_products',
            field=models.ManyToManyField(blank=True, help_text='Select products to display as related items on this post.', related_name='related_posts', to='product.product'),
        ),
    ]
