# Generated by Django 4.2.26 on 2025-11-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_related_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='related_products_title',
            field=models.CharField(blank=True, default='Related Products', help_text="Title to display above the related products section (e.g., 'Recommended for You').", max_length=255),
        ),
    ]
