# Generated by Django 4.2.27 on 2025-12-22 12:10

from django.db import migrations, models
import order.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(default=order.models.generate_order_id, editable=False, max_length=8, primary_key=True, serialize=False),
        ),
    ]
