# Generated by Django 4.2.27 on 2026-01-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, help_text='The selected payment method (e.g., COD).', max_length=50, null=True),
        ),
    ]
