# Generated by Django 4.2.29 on 2026-03-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_manual_order_platform_and_actual_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='profit',
            field=models.DecimalField(decimal_places=2, editable=False, help_text='(effective_unit_price - landed_cost) * quantity', max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, help_text='Unit price at time of sale; for manual orders equals actual_unit_price.', max_digits=10),
        ),
    ]
