# Generated by Django 4.2.25 on 2026-05-11 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0011_order_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashBankReceiptEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('CASH', 'Cash received'), ('BANK', 'Bank transfer')], max_length=10)),
                ('received_from', models.CharField(help_text='Payer or source description.', max_length=255)),
                ('transaction_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_bank_receipt_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['transaction_date', 'id'],
            },
        ),
    ]
