# Generated by Django 4.2.25 on 2026-06-25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0013_agent_commission_payment_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbankreceiptentry',
            name='payment_type',
            field=models.CharField(
                choices=[
                    ('CASH', 'Cash received'),
                    ('BANK', 'Bank transfer'),
                    ('LOAN', 'Loan repayment'),
                ],
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name='RevenueAdjustmentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(
                    choices=[
                        ('COMMISSION_RELEASED', 'Commission released'),
                        ('LOAN_INTEREST', 'Interest of loan'),
                    ],
                    max_length=20,
                )),
                ('reference', models.CharField(help_text='Description or reference.', max_length=255)),
                ('transaction_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='revenue_adjustment_entries',
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={
                'ordering': ['transaction_date', 'id'],
            },
        ),
    ]
