# Generated by Django 4.2.25 on 2025-11-08 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commission', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionledger',
            name='order_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='commission_record', to='order.orderitem'),
        ),
    ]
