# Generated by Django 4.2.27 on 2025-12-22 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Image Category',
                'verbose_name_plural': 'Image Categories',
                'db_table': 'blog_imagecategory',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MediaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g., 'Red Scarf Product Shot'", max_length=200)),
                ('image', models.ImageField(upload_to='blog_gallery/')),
                ('alt_text', models.CharField(blank=True, help_text='Accessibility text for screen readers.', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.imagecategory')),
            ],
            options={
                'db_table': 'blog_mediaimage',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
