# Generated by Django 4.2.27 on 2025-12-19 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Short summary of the plan.')),
                ('features', models.JSONField(blank=True, default=list, help_text="List of features features strings, e.g. ['10% Commission', 'Priority Support']")),
                ('is_active', models.BooleanField(default=True)),
                ('is_popular', models.BooleanField(default=False, help_text='Highlight this plan in the UI.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordering for display.')),
                ('target_group', models.ForeignKey(help_text='The user group (and commission %) assigned when this plan is selected.', on_delete=django.db.models.deletion.PROTECT, related_name='subscription_plans', to='user.usergroup')),
            ],
            options={
                'ordering': ['order', 'price'],
            },
        ),
    ]
