# Generated by Django 4.2.25 on 2025-11-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='The percentage of the *profit* this group earns as commission (e.g., 50.00 for 50%).', max_digits=5),
        ),
    ]
