# Generated by Django 4.2.27 on 2025-12-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='shipping_address',
            field=models.TextField(blank=True, help_text='Default shipping address for orders.'),
        ),
    ]
