# Generated by Django 4.2.25 on 2025-10-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Agent Tiers', 'Customer Types'", max_length=100, unique=True)),
                ('product_categories', models.ManyToManyField(blank=True, related_name='user_groups', to='product.category')),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='categories',
        ),
        migrations.DeleteModel(
            name='UserCategory',
        ),
        migrations.DeleteModel(
            name='UserCategoryGroup',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_groups',
            field=models.ManyToManyField(blank=True, related_name='users', to='user.usergroup'),
        ),
    ]
