# Generated by Django 4.2.27 on 2026-01-12 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, help_text='Select the agent responsible for this customer. This agent will receive commissions on orders.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downline_customers', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Agent (Upline)'),
        ),
    ]
