# Generated by Django 4.2.25 on 2025-10-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usergroup_remove_customuser_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Set this as the default group for new users.'),
        ),
    ]
