# Generated by Django 4.2.27 on 2025-12-19 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_subscriptionplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='description',
            field=models.TextField(blank=True, help_text="Use '|' to split languages."),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(help_text="Use '|' to split languages (e.g., 'Gold Plan | 金牌套餐')", max_length=100),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='target_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_plans', to='user.usergroup'),
        ),
    ]
