# Generated by Django 4.2.25 on 2025-10-21 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_customuser_is_verified_customuser_verification_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='verification_code',
        ),
    ]
