# Generated by Django 4.2.26 on 2025-11-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Top line (e.g., 'Free Shipping')", max_length=50)),
                ('subtitle', models.CharField(blank=True, help_text="Bottom line (e.g., 'Orders over $100')", max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display (1-4 recommended)')),
            ],
            options={
                'verbose_name': 'Global Product Feature',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Distributor Platform', max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('contact_address', models.TextField(blank=True, help_text='Physical address displayed in footer.')),
                ('footer_about_text', models.TextField(blank=True, help_text='A short paragraph about your company displayed in the footer.')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter/X URL')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
