# Generated by Django 4.2.28 on 2026-02-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='login_btn_text',
            field=models.CharField(default='登录 | Sign In', help_text='Label for the Sign In button.', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='login_error_text',
            field=models.CharField(default="用户名或密码不匹配，请重试。 | Your username and password didn't match. Please try again.", help_text='Error message displayed when login fails.', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='login_heading',
            field=models.CharField(default='登录您的账户 | Sign in to your account', help_text='Main heading on the login card.', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='login_password_placeholder',
            field=models.CharField(default='密码 | Password', help_text='Placeholder for the password input.', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='login_register_text',
            field=models.CharField(default='或注册新账户 | Or register for a new account', help_text='Link text to the registration page.', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='login_title',
            field=models.CharField(default='登录 | Sign In', help_text='Browser tab title for the login page.', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='login_username_placeholder',
            field=models.CharField(default='用户名 | Username', help_text='Placeholder for the username input.', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='nav_login_text',
            field=models.CharField(default='登录 | Login', help_text="Label for the 'Login' link in the top navigation.", max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='nav_register_text',
            field=models.CharField(default='注册 | Register', help_text="Label for the 'Register' button in the top navigation.", max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='order_history_title',
            field=models.CharField(default='订单记录 | Order History', help_text='Title for the Order History table.', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='register_btn_text',
            field=models.CharField(default='注册 | Register', help_text='Label for the Register button.', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='register_email_placeholder',
            field=models.CharField(default='电子邮件 | Email', help_text='Placeholder for the email input.', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='register_heading',
            field=models.CharField(default='创建您的账户 | Create your account', help_text='Main heading on the register card.', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='register_password_placeholder',
            field=models.CharField(default='密码 | Password', help_text='Placeholder for the password input.', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='register_phone_placeholder',
            field=models.CharField(default='电话号码 | Phone Number', help_text='Placeholder for the phone number input.', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='register_signin_text',
            field=models.CharField(default='已有账户？登录 | Already have an account? Sign in', help_text='Link text to redirect to the login page.', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='register_title',
            field=models.CharField(default='注册 | Join Us', help_text='Browser tab title for the register page.', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='register_username_placeholder',
            field=models.CharField(default='用户名 | Username', help_text='Placeholder for the username input.', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='subscription_subtitle',
            field=models.CharField(default='升级代理身份，解锁更高佣金和专属功能。 | Unlock higher commissions and exclusive features by upgrading your agent status.', help_text='Subtitle for the Subscription Plans page.', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='subscription_title',
            field=models.CharField(default='选择适合您的计划 | Choose the right plan for you', help_text='Title for the Subscription Plans page.', max_length=100),
        ),
    ]
