# Generated by Django 4.2.26 on 2025-12-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='site_logo',
            field=models.ImageField(blank=True, help_text='Upload a logo to display next to the site name in the navigation bar.', null=True, upload_to='site_branding/'),
        ),
    ]
