# Generated by Django 4.2.26 on 2025-11-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Top line (e.g., 'Free Shipping')", max_length=50)),
                ('subtitle', models.CharField(blank=True, help_text="Bottom line (e.g., 'Orders over $100')", max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display (1-4 recommended)')),
            ],
            options={
                'verbose_name': 'Global Product Feature',
                'ordering': ['order'],
            },
        ),
    ]
