# Generated by Django 4.2.27 on 2025-12-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='agent_dashboard_title',
            field=models.CharField(default='代理仪表板 | Agent Dashboard', help_text='Title for the Agent Dashboard section.', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='agent_stats_earnings_text',
            field=models.CharField(default='总收入 (累计) | Total Earnings (All Time)', help_text='Label for the Total Earnings stat card.', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='footer_col2_title',
            field=models.CharField(default='主要链接 | Quick Links', help_text='Title for the second column in the footer.', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='footer_col3_title',
            field=models.CharField(default='產品分類 | Product Categories', help_text='Title for the third column (Categories) in the footer.', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='footer_col4_title',
            field=models.CharField(default='联系我們 | Contact Us', help_text='Title for the fourth column (Contact Info) in the footer.', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='footer_link_account_text',
            field=models.CharField(default='我的账户 | My Account', help_text="Label for the 'My Account' link in the footer.", max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='footer_link_blog_text',
            field=models.CharField(default='市场热报 | Market Insights', help_text="Label for the 'Market Insights' link in the footer.", max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='footer_link_home_text',
            field=models.CharField(default='主页 | Home', help_text="Label for the 'Home' link in the footer.", max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='footer_link_products_text',
            field=models.CharField(default='所有产品 | All Products', help_text="Label for the 'All Products' link in the footer.", max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='homepage_view_all_text',
            field=models.CharField(default='查看全部 | View All', help_text="Label for 'View All' links on the homepage category sections.", max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='mobile_nav_account_text',
            field=models.CharField(default='账户 | Account', help_text="Label for 'Account' in mobile bottom nav.", max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='mobile_nav_login_text',
            field=models.CharField(default='登录 | Login', help_text="Label for 'Login' in mobile bottom nav.", max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='mobile_nav_order_text',
            field=models.CharField(default='下单 | Order', help_text="Label for 'Order' in mobile bottom nav.", max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='mobile_nav_products_text',
            field=models.CharField(default='产品 | Products', help_text="Label for 'Products' in mobile bottom nav.", max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='place_order_add_text',
            field=models.CharField(default='加入购物车 | Add to Cart', help_text="Label for the 'Add' button in the order table.", max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='place_order_added_text',
            field=models.CharField(default='已加入购物车 | Added', help_text="Label for the 'Added' button state in the order table.", max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='place_order_empty_cart_text',
            field=models.CharField(default='您的购物车是空的。 | Your cart is empty.', help_text='Message displayed when the cart is empty in the order summary.', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='place_order_search_placeholder',
            field=models.CharField(default='按名称 or SKU 搜索... | Search products by name or SKU...', help_text='Placeholder text for the search bar.', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='place_order_title',
            field=models.CharField(default='建立新订单 | Place a New Order', help_text='Main title on the Place Order page.', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='price_on_request_text',
            field=models.CharField(default='Price available upon request. | 价格面议', help_text='Label displayed when a product has no price set.', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='product_action_details_text',
            field=models.CharField(default='详情 | Details', help_text="Label for the 'Details' button (Quick View modal).", max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='product_action_enquire_text',
            field=models.CharField(default='询问 | Enquire', help_text="Label for the 'Enquire' button (WhatsApp).", max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='product_action_share_text',
            field=models.CharField(default=' 分享| Share', help_text="Label for the 'Share' button.", max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='profile_hello_text',
            field=models.CharField(default='你好 | Hello', help_text='Greeting text before the username.', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='profile_signout_text',
            field=models.CharField(default='退出 | Sign Out', help_text='Label for the Sign Out button.', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='sidebar_news_title',
            field=models.CharField(default='最新消息 | Latest News', help_text='Title for the News widget in the sidebar (Product List/Detail pages).', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='special_promotions_subtitle',
            field=models.CharField(default='限时独家优惠。 | Exclusive deals available for a limited time.', help_text='Subtitle/Description under the Promotions title.', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='special_promotions_title',
            field=models.CharField(default='特别优惠 | Special Promotions', help_text='Title for the Promotions section on the product list page.', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='user_menu_profile_text',
            field=models.CharField(default='个人资料 | Your Profile', help_text="Label for 'Your Profile' link in the user dropdown.", max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='user_menu_settings_text',
            field=models.CharField(default='设置 | Settings', help_text="Label for 'Settings' link in the user dropdown.", max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='user_menu_signed_in_text',
            field=models.CharField(default='登录为 | Signed in as', help_text="Label for 'Signed in as' in the user dropdown.", max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='user_menu_signout_text',
            field=models.CharField(default='退出 | Sign out', help_text="Label for 'Sign out' button in the user dropdown.", max_length=100),
        ),
    ]
