# Generated by Django 4.2.26 on 2025-12-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesetting_site_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='nav_background_color',
            field=models.CharField(default='#FFFFFF', help_text='Select the background color for the top navigation bar.', max_length=7),
        ),
    ]
