# Generated by Django 4.2.27 on 2025-12-23 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sitesetting_agent_dashboard_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='checkout_back_btn',
            field=models.CharField(default='Back to Cart|返回购物车', help_text="Use '|' to separate lines.", max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='checkout_col_price',
            field=models.CharField(default='Unit Price|单价', help_text="Use '|' to separate lines.", max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='checkout_col_product',
            field=models.CharField(default='Product|产品', help_text="Use '|' to separate lines.", max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='checkout_col_qty',
            field=models.CharField(default='Qty|数量', help_text="Use '|' to separate lines.", max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='checkout_col_total',
            field=models.CharField(default='Total|总计', help_text="Use '|' to separate lines.", max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='checkout_commission_label',
            field=models.CharField(default='Estimated Commission:|预计佣金：', help_text="Use '|' to separate lines.", max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='checkout_confirm_btn',
            field=models.CharField(default='Confirm Order|确认订单', help_text="Use '|' to separate lines.", max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='checkout_empty_msg',
            field=models.CharField(default='Your checkout session is empty or expired.|您的结账会话为空或已过期。', help_text="Use '|' to separate lines.", max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='checkout_return_btn',
            field=models.CharField(default='Return to Order Page|返回订单页面', help_text="Use '|' to separate lines.", max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='checkout_summary_title',
            field=models.CharField(default='Order Summary|订单摘要', help_text="Use '|' to separate lines.", max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='checkout_title',
            field=models.CharField(default='Checkout Confirmation|结账确认', help_text="Use '|' to separate lines.", max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='checkout_total_label',
            field=models.CharField(default='Total:|总计：', help_text="Use '|' to separate lines.", max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='agent_stats_paid_text',
            field=models.CharField(default='已付金额 | Paid Out', help_text='Label for the Paid Out stat card.', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='agent_stats_pending_text',
            field=models.CharField(default='待付金额 | Pending Payout', help_text='Label for the Pending Payout stat card.', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='commission_history_title',
            field=models.CharField(default='佣金记录 | Commission History', help_text='Title for the Commission History table.', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='place_order_header_price',
            field=models.CharField(default='售价 | Selling Price', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='place_order_header_product',
            field=models.CharField(default='产品 | Product', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='place_order_header_profit',
            field=models.CharField(default='您的利润 | Your Profit', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='price_on_request_text',
            field=models.CharField(default='价格面议 | Price available upon request.', help_text='Label displayed when a product has no price set.', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='verify_btn_text',
            field=models.CharField(default='验证账户 | Verify Account', help_text='Label for the Verify button.', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='verify_modal_title',
            field=models.CharField(default='验证邮件账号 | Verify your email', help_text='Title for the OTP verification modal.', max_length=100),
        ),
    ]
