# Generated by Django 4.2.28 on 2026-02-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sitesetting_login_btn_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Upload a 16x16 or 32x32 pixel image (PNG/ICO/WEBP) to use as the browser tab icon.', null=True, upload_to='site_branding/favicons/'),
        ),
    ]
