# Generated by Django 4.2.26 on 2025-12-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesetting_nav_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='announcements_title',
            field=models.CharField(default='Announcements', help_text='Title for the Announcements widget.', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='faq_section_title',
            field=models.CharField(default='Frequently Asked Questions', help_text='Title for the FAQ section.', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='market_insights_title',
            field=models.CharField(default='Market Insights', help_text='Title for the Sidebar Insights widget.', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='news_section_title',
            field=models.CharField(default='Latest News', help_text="Title for the News section (e.g., 'Latest News', 'Our Story', 'Blog').", max_length=100),
        ),
    ]
