# Generated by Django 4.2.27 on 2025-12-23 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesetting_checkout_back_btn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='customer_service_whatsapp',
            field=models.CharField(default='60199333030', help_text="Format: 60123456789 (No '+' or dashes). Agent orders will be sent here.", max_length=20),
        ),
    ]
