# Generated by Django 4.2.27 on 2025-12-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesetting_customer_service_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='user_menu_profile_text',
            field=models.CharField(default='订单记录 | Order History', help_text='Label for the link pointing to the Order History page (formerly Profile).', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='user_menu_settings_text',
            field=models.CharField(default='个人资料 | Profile', help_text='Label for the link pointing to User Profile settings.', max_length=100),
        ),
    ]
