# Generated by Django 4.2.26 on 2025-12-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesetting_announcements_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='nav_background_color',
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='news_section_title',
            field=models.CharField(default='Latest News', help_text="Title for the News section. Use '|' for two lines (e.g., 'Latest News | 最新消息').", max_length=100),
        ),
    ]
