# Generated by Django 4.2.26 on 2025-12-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_sitesetting_nav_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='footer_col2_title',
            field=models.CharField(default='Quick Links | 快速链接', help_text='Title for the second column in the footer.', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_link_account_text',
            field=models.CharField(default='My Account | 我的账户', help_text="Label for the 'My Account' link in the footer.", max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_link_blog_text',
            field=models.CharField(default='Market Insights | 市场咨询', help_text="Label for the 'Market Insights' link in the footer.", max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_link_home_text',
            field=models.CharField(default='Home | 主页', help_text="Label for the 'Home' link in the footer.", max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_link_products_text',
            field=models.CharField(default='All Products | 所有产品', help_text="Label for the 'All Products' link in the footer.", max_length=100),
        ),
    ]
