# Generated by Django 4.2.27 on 2026-01-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_sitesetting_user_menu_profile_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='settings_btn_cancel',
            field=models.CharField(default='Cancel | 取消', help_text='Button text for Cancel.', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='settings_btn_change_pwd',
            field=models.CharField(default='Change Password | 更改密码', help_text='Button text for Change Password.', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='settings_btn_edit',
            field=models.CharField(default='Edit | 编辑', help_text='Button text for Edit.', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='settings_btn_save',
            field=models.CharField(default='Save Changes | 保存更改', help_text='Button text for Save.', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='settings_label_address',
            field=models.CharField(default='Shipping Address | 收货地址', help_text='Label for Address.', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='settings_label_confirm_pwd',
            field=models.CharField(default='Confirm New Password | 确认新密码', help_text='Label for Confirm Password.', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='settings_label_current_pwd',
            field=models.CharField(default='Current Password | 当前密码', help_text='Label for Current Password.', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='settings_label_email',
            field=models.CharField(default='Email Address | 电子邮件', help_text='Label for Email.', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='settings_label_first_name',
            field=models.CharField(default='First Name | 名', help_text='Label for First Name.', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='settings_label_last_name',
            field=models.CharField(default='Last Name | 姓', help_text='Label for Last Name.', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='settings_label_new_pwd',
            field=models.CharField(default='New Password | 新密码', help_text='Label for New Password.', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='settings_label_phone',
            field=models.CharField(default='Phone Number | 电话号码', help_text='Label for Phone.', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='settings_page_title',
            field=models.CharField(default='Account Settings | 账户设置', help_text='Main title for the Settings page.', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='settings_profile_title',
            field=models.CharField(default='Profile Information | 个人资料', help_text='Header for the Profile section.', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='settings_security_desc',
            field=models.CharField(default='Update your password to keep your account secure. | 更新您的密码以保持账户安全。', help_text='Description under Security header.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='settings_security_title',
            field=models.CharField(default='Security | 安全设置', help_text='Header for the Security section.', max_length=100),
        ),
    ]
