# Generated by Django 4.2.26 on 2025-12-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sitesetting_footer_col2_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='market_insights_nav_text',
            field=models.CharField(default='Market Insights | 市场咨询', help_text="Label for the 'Market Insights' link in the main navigation.", max_length=100),
        ),
    ]
