# Generated by Django 4.2.27 on 2026-01-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sitesetting_settings_btn_cancel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name (e.g., 'Online Banking', 'COD').", max_length=100)),
                ('option_type', models.CharField(choices=[('GATEWAY', 'Online Gateway (Uses Site Config)'), ('COD', 'Cash On Delivery'), ('MANUAL', 'Manual / Bank Transfer')], default='GATEWAY', help_text='GATEWAY triggers the active online provider. COD/MANUAL just records the order.', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Instructions displayed to the user (e.g. Bank details).')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Payment Option',
                'verbose_name_plural': 'Payment Options',
            },
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='payment_api_key',
            field=models.CharField(blank=True, help_text='Your Secret Key (SenangPay) or API Key.', max_length=255, verbose_name='Secret Key / API Key'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='payment_category_code',
            field=models.CharField(blank=True, help_text='Required: Merchant ID (SenangPay) or Collection ID (Billplz).', max_length=100, verbose_name='Merchant ID / Collection ID'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='payment_provider',
            field=models.CharField(choices=[('SENANGPAY', 'SenangPay (FPX/Credit Card)'), ('BILLPLZ', 'Billplz (FPX/Malaysia)'), ('STRIPE', 'Stripe (Credit Card)')], default='SENANGPAY', help_text='Select the logic handler for processing payments.', max_length=20),
        ),
    ]
