# Generated by Django 4.2.26 on 2025-12-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sitesetting_market_insights_nav_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='footer_col3_title',
            field=models.CharField(default='Product Categories | 產品分類', help_text='Title for the third column (Categories) in the footer.', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_col4_title',
            field=models.CharField(default='Contact Us | 關注我們', help_text='Title for the fourth column (Contact Info) in the footer.', max_length=100),
        ),
    ]
