# Generated by Django 4.2.26 on 2025-12-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sitesetting_footer_col3_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='mobile_nav_account_text',
            field=models.CharField(default='Account | 账户', help_text="Label for 'Account' in mobile bottom nav.", max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='mobile_nav_login_text',
            field=models.CharField(default='Login | 登录', help_text="Label for 'Login' in mobile bottom nav.", max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='mobile_nav_order_text',
            field=models.CharField(default='Order | 下单', help_text="Label for 'Order' in mobile bottom nav.", max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='mobile_nav_products_text',
            field=models.CharField(default='Products | 产品', help_text="Label for 'Products' in mobile bottom nav.", max_length=50),
        ),
    ]
