# Generated by Django 4.2.26 on 2025-12-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sitesetting_mobile_nav_account_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='user_menu_profile_text',
            field=models.CharField(default='Your Profile | 个人资料', help_text="Label for 'Your Profile' link in the user dropdown.", max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='user_menu_settings_text',
            field=models.CharField(default='Settings | 设置', help_text="Label for 'Settings' link in the user dropdown.", max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='user_menu_signed_in_text',
            field=models.CharField(default='Signed in as | 登录身份', help_text="Label for 'Signed in as' in the user dropdown.", max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='user_menu_signout_text',
            field=models.CharField(default='Sign out | 退出登录', help_text="Label for 'Sign out' button in the user dropdown.", max_length=100),
        ),
    ]
