# Generated by Django 4.2.26 on 2025-12-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_sitesetting_user_menu_profile_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='place_order_btn_label',
            field=models.CharField(default='Place Order | 下单', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='place_order_est_profit_label',
            field=models.CharField(default='Estimated Profit: | 预计利润:', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='place_order_header_price',
            field=models.CharField(default='Selling Price | 售价', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='place_order_header_product',
            field=models.CharField(default='Product | 产品', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='place_order_header_profit',
            field=models.CharField(default='Your Profit | 您的利润', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='place_order_header_sku',
            field=models.CharField(default='SKU', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='place_order_search_placeholder',
            field=models.CharField(default='Search products by name or SKU... | 按名称 or SKU 搜索...', help_text='Placeholder text for the search bar.', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='place_order_summary_title',
            field=models.CharField(default='Order Summary | 订单摘要', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='place_order_title',
            field=models.CharField(default='Place a New Order | 下新订单', help_text='Main title on the Place Order page.', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='place_order_total_label',
            field=models.CharField(default='Total Price: | 总价:', max_length=50),
        ),
    ]
