# Generated by Django 4.2.26 on 2025-12-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_sitesetting_place_order_btn_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='sidebar_news_title',
            field=models.CharField(default='Latest News | 最新消息', help_text='Title for the News widget in the sidebar (Product List/Detail pages).', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='sidebar_search_title',
            field=models.CharField(default='Search Products | 搜索产品', help_text='Title for the Search widget in the sidebar.', max_length=100),
        ),
    ]
