# Generated by Django 4.2.26 on 2025-12-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_sitesetting_sidebar_news_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='sidebar_search_button_text',
            field=models.CharField(default='Search | 搜索', help_text='Label for the sidebar search button.', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='sidebar_search_placeholder',
            field=models.CharField(default='Search by keyword... | 按关键字搜索...', help_text='Placeholder text for the sidebar search input.', max_length=100),
        ),
    ]
