# Generated by Django 4.2.26 on 2025-12-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_sitesetting_sidebar_search_button_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='special_promotions_title',
            field=models.CharField(default='Special Promotions | 特别优惠', help_text='Title for the Promotions section on the product list page.', max_length=100),
        ),
    ]
