# Generated by Django 4.2.26 on 2025-12-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_sitesetting_special_promotions_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='special_promotions_subtitle',
            field=models.CharField(default='Exclusive deals available for a limited time. | 限时独家优惠。', help_text='Subtitle/Description under the Promotions title.', max_length=255),
        ),
    ]
