# Generated by Django 4.2.26 on 2025-12-04 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_sitesetting_special_promotions_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='product_action_details_text',
            field=models.CharField(default='Details | 详情', help_text="Label for the 'Details' button (Quick View modal).", max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='product_action_enquire_text',
            field=models.CharField(default='Enquire | 咨询', help_text="Label for the 'Enquire' button (WhatsApp).", max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='product_action_share_text',
            field=models.CharField(default='Share | 分享', help_text="Label for the 'Share' button.", max_length=50),
        ),
    ]
