# Generated by Django 4.2.26 on 2025-12-04 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_sitesetting_product_action_details_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='price_on_request_text',
            field=models.CharField(default='Price available upon request. | 价格面议。', help_text='Label displayed when a product has no price set.', max_length=100),
        ),
    ]
