# Generated by Django 4.2.26 on 2025-12-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_sitesetting_price_on_request_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='login_required_text',
            field=models.CharField(default='需要登录 | Login required', help_text='Label displayed when user must login to view price.', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='view_details_text',
            field=models.CharField(default='查看详情 | View Details', help_text="Label for 'View Details' links (e.g., in promotions).", max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='price_on_request_text',
            field=models.CharField(default='价格面议 | Price available upon request.', help_text='Label displayed when a product has no price set.', max_length=100),
        ),
    ]
