# Generated by Django 4.2.26 on 2025-12-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_sitesetting_login_required_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='homepage_view_all_text',
            field=models.CharField(default='View All | 查看全部', help_text="Label for 'View All' links on the homepage category sections.", max_length=50),
        ),
    ]
