# Generated by Django 4.2.26 on 2025-12-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_sitesetting_homepage_view_all_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='place_order_add_text',
            field=models.CharField(default='Add | 添加', help_text="Label for the 'Add' button in the order table.", max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='place_order_added_text',
            field=models.CharField(default='Added | 已加', help_text="Label for the 'Added' button state in the order table.", max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='place_order_empty_cart_text',
            field=models.CharField(default='Your cart is empty. | 您的购物车是空的。', help_text='Message displayed when the cart is empty in the order summary.', max_length=100),
        ),
    ]
