# Generated by Django 4.2.26 on 2025-12-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_sitesetting_place_order_add_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='agent_dashboard_title',
            field=models.CharField(default='Agent Dashboard | 代理仪表板', help_text='Title for the Agent Dashboard section.', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='agent_stats_earnings_text',
            field=models.CharField(default='Total Earnings (All Time) | 总收入 (累计)', help_text='Label for the Total Earnings stat card.', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='agent_stats_paid_text',
            field=models.CharField(default='Paid Out | 已付金额', help_text='Label for the Paid Out stat card.', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='agent_stats_pending_text',
            field=models.CharField(default='Pending Payout | 待付金额', help_text='Label for the Pending Payout stat card.', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='commission_history_title',
            field=models.CharField(default='Commission History | 佣金记录', help_text='Title for the Commission History table.', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='order_history_title',
            field=models.CharField(default='Order History | 订单记录', help_text='Title for the Order History table.', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='profile_hello_text',
            field=models.CharField(default='Hello | 你好', help_text='Greeting text before the username.', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='profile_signout_text',
            field=models.CharField(default='Sign Out | 退出', help_text='Label for the Sign Out button.', max_length=50),
        ),
    ]
