# Generated by Django 4.2.26 on 2025-12-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_sitesetting_agent_dashboard_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='nav_login_text',
            field=models.CharField(default='Login | 登录', help_text="Label for the 'Login' link in the top navigation.", max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='nav_register_text',
            field=models.CharField(default='Register | 注册', help_text="Label for the 'Register' button in the top navigation.", max_length=50),
        ),
    ]
