# Generated by Django 4.2.26 on 2025-12-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_sitesetting_nav_login_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='login_btn_text',
            field=models.CharField(default='Sign In | 登录', help_text='Label for the Sign In button.', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='login_error_text',
            field=models.CharField(default="Your username and password didn't match. Please try again. | 用户名或密码不匹配，请重试。", help_text='Error message displayed when login fails.', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='login_heading',
            field=models.CharField(default='Sign in to your account | 登录您的账户', help_text='Main heading on the login card.', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='login_password_placeholder',
            field=models.CharField(default='Password | 密码', help_text='Placeholder for the password input.', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='login_register_text',
            field=models.CharField(default='Or register for a new account | 或注册新账户', help_text='Link text to the registration page.', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='login_title',
            field=models.CharField(default='Sign In | 登录', help_text='Browser tab title for the login page.', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='login_username_placeholder',
            field=models.CharField(default='Username | 用户名', help_text='Placeholder for the username input.', max_length=50),
        ),
    ]
