# Generated by Django 4.2.26 on 2025-12-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_sitesetting_login_btn_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='register_btn_text',
            field=models.CharField(default='Register | 注册', help_text='Label for the Register button.', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='register_email_placeholder',
            field=models.CharField(default='Email | 电子邮件', help_text='Placeholder for the email input.', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='register_heading',
            field=models.CharField(default='Create your account | 创建您的账户', help_text='Main heading on the register card.', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='register_password_placeholder',
            field=models.CharField(default='Password | 密码', help_text='Placeholder for the password input.', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='register_phone_placeholder',
            field=models.CharField(default='Phone Number | 电话号码', help_text='Placeholder for the phone number input.', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='register_signin_text',
            field=models.CharField(default='Already have an account? Sign in | 已有账户？登录', help_text='Link text to redirect to the login page.', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='register_title',
            field=models.CharField(default='Join Us | 注册', help_text='Browser tab title for the register page.', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='register_username_placeholder',
            field=models.CharField(default='Username | 用户名', help_text='Placeholder for the username input.', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='verify_btn_text',
            field=models.CharField(default='Verify Account | 验证账户', help_text='Label for the Verify button.', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='verify_modal_title',
            field=models.CharField(default='Verify your phone | 验证手机', help_text='Title for the OTP verification modal.', max_length=100),
        ),
    ]
