# Generated by Django 4.2.27 on 2025-12-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_sitesetting_register_btn_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('HOME_HERO', 'Home Page Hero | 首页横幅'), ('GLOBAL_TOP', 'Global Top Banner (Category Nav) | 全局顶部横幅')], default='HOME_HERO', help_text='Where this banner should appear.', max_length=20)),
                ('title', models.CharField(blank=True, help_text='Main heading text.', max_length=200)),
                ('subtitle', models.TextField(blank=True, help_text='Subtitle or description text.')),
                ('background_image', models.ImageField(blank=True, help_text='Background image for the banner.', null=True, upload_to='banners/')),
                ('button_text', models.CharField(blank=True, help_text='Text for the call-to-action button.', max_length=50)),
                ('button_link', models.CharField(blank=True, help_text="URL or path for the button (e.g., '/products/').", max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this banner.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of priority if multiple are active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['location', 'order', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='verify_modal_title',
            field=models.CharField(default='Verify your email | 验证邮件账号', help_text='Title for the OTP verification modal.', max_length=100),
        ),
    ]
