# Generated by Django 4.2.27 on 2025-12-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_banner_alter_sitesetting_verify_modal_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['location', 'order', '-created_at'], 'verbose_name': 'Banner / Hero Image'},
        ),
        migrations.AddField(
            model_name='banner',
            name='content_position',
            field=models.CharField(choices=[('left-top', 'Top Left'), ('center-top', 'Top Center'), ('right-top', 'Top Right'), ('left-middle', 'Middle Left'), ('center-middle', 'Middle Center'), ('right-middle', 'Middle Right'), ('left-bottom', 'Bottom Left'), ('center-bottom', 'Bottom Center'), ('right-bottom', 'Bottom Right')], default='center-middle', help_text='Position of the text content.', max_length=20),
        ),
        migrations.AlterField(
            model_name='banner',
            name='button_link',
            field=models.CharField(blank=True, help_text='URL or path for the button.', max_length=200),
        ),
        migrations.AlterField(
            model_name='banner',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of priority.'),
        ),
    ]
