# Generated by Django 4.2.27 on 2025-12-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_banner_options_banner_content_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='background_color',
            field=models.CharField(default='#312E81', help_text='Hex color code (e.g., #312E81) used if no image is provided or as a fallback.', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='announcements_title',
            field=models.CharField(default='布告栏 | Announcements', help_text='Title for the Announcements widget.', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='market_insights_nav_text',
            field=models.CharField(default='市场热报 | Market Insights', help_text="Label for the 'Market Insights' link in the main navigation.", max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='market_insights_title',
            field=models.CharField(default='市场热报 | Market Insights', help_text='Title for the Sidebar Insights widget.', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='news_section_title',
            field=models.CharField(default='最近更新 | Latest News', help_text='Title for the News section.', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='sidebar_search_button_text',
            field=models.CharField(default='搜索 | Search', help_text='Label for the sidebar search button.', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='sidebar_search_placeholder',
            field=models.CharField(default='关键字搜索... | Search by keyword...', help_text='Placeholder text for the sidebar search input.', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='sidebar_search_title',
            field=models.CharField(default='搜索产品 | Search Products', help_text='Title for the Search widget in the sidebar.', max_length=100),
        ),
    ]
