# Generated by Django 4.2.27 on 2025-12-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_banner_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='background_opacity',
            field=models.PositiveIntegerField(default=90, help_text='Opacity percentage (0-100). 0 is transparent, 100 is solid.'),
        ),
    ]
