# Generated by Django 4.2.27 on 2025-12-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_banner_background_opacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='featured_products_title',
            field=models.CharField(default='必看产品 | Featured Products', help_text='Title for the Featured Products section on the homepage.', max_length=100),
        ),
    ]
