# Generated by Django 4.2.27 on 2025-12-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_sitesetting_featured_products_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='location',
            field=models.CharField(choices=[('HOME_HERO', 'Home Page Hero | 首页横幅'), ('HOME_SUB', 'Home Sub-Feature (Side-by-Side) | 首页副横幅'), ('GLOBAL_TOP', 'Global Top Banner (Category Nav) | 全局顶部横幅')], default='HOME_HERO', help_text='Where this banner should appear.', max_length=20),
        ),
    ]
