# Generated by Django 4.2.27 on 2025-12-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_banner_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='nav_background_color',
            field=models.CharField(default='#FFFFFF', help_text='Hex color code for the top navigation bar (e.g., #FFFFFF).', max_length=7),
        ),
    ]
