# Generated by Django 4.2.27 on 2025-12-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_sitesetting_nav_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='category_header_background_color',
            field=models.CharField(default='#C7D2FE', help_text='Background color for the category header on the product list page.', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='category_header_border_color',
            field=models.CharField(default='#C7D2FE', help_text='Border color for the category header.', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='category_header_subtitle_color',
            field=models.CharField(default='#4F46E5', help_text="Text color for the category subtitle (if using '|' separator).", max_length=7),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='category_header_title_color',
            field=models.CharField(default='#3730A3', help_text='Text color for the category main title.', max_length=7),
        ),
    ]
