# Generated by Django 4.2.27 on 2025-12-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_sitesetting_category_header_background_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeSetting',
            fields=[
            ],
            options={
                'verbose_name': 'Theme & Color Settings',
                'verbose_name_plural': 'Theme & Color Settings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesetting',),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='category_header_background_color',
            field=models.CharField(default='#C7D2FE', help_text='Background color for the category header.', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='category_header_subtitle_color',
            field=models.CharField(default='#4F46E5', help_text='Text color for the category subtitle.', max_length=7),
        ),
    ]
