# Generated by Django 4.2.27 on 2025-12-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_themesetting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='section_header_background_color',
            field=models.CharField(default='#E0E7FF', help_text='Background color for extra content section headers.', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='section_header_border_color',
            field=models.CharField(default='#E0E7FF', help_text='Border color for extra content section headers.', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='section_header_title_color',
            field=models.CharField(default='#3730A3', help_text='Text color for extra content section headers.', max_length=7),
        ),
    ]
