# Generated by Django 4.2.27 on 2025-12-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_sitesetting_section_header_background_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='site_name',
            field=models.CharField(default='Distributor Platform', help_text="The name of your site. Use '|' to split into two lines (e.g., 'English Name | Chinese Name').", max_length=100),
        ),
    ]
