# Generated by Django 4.2.27 on 2025-12-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_sitesetting_site_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='site_name_color',
            field=models.CharField(default='#4F46E5', help_text='Color for the main site name text.', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site_name_subtitle_color',
            field=models.CharField(default='#818CF8', help_text='Color for the site name subtitle (second line).', max_length=7),
        ),
    ]
