# Generated by Django 4.2.27 on 2025-12-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_sitesetting_site_name_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='subscription_subtitle',
            field=models.CharField(default='Unlock higher commissions and exclusive features by upgrading your agent status. | 升级代理身份，解锁更高佣金和专属功能。', help_text='Subtitle for the Subscription Plans page.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='subscription_title',
            field=models.CharField(default='Choose the right plan for you | 选择适合您的计划', help_text='Title for the Subscription Plans page.', max_length=100),
        ),
    ]
