# Generated by Django 4.2.27 on 2025-12-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_sitesetting_site_name_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='place_order_summary_background_color',
            field=models.CharField(default='#FFFFFF', help_text='Background color for the Order Summary box.', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='place_order_summary_border_color',
            field=models.CharField(default='#E5E7EB', help_text='Border color for the Order Summary box.', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='place_order_summary_text_color',
            field=models.CharField(default='#4B5563', help_text='Default text color for labels in the Order Summary.', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='place_order_summary_title_color',
            field=models.CharField(default='#111827', help_text='Text color for the Order Summary title.', max_length=7),
        ),
    ]
