# Generated by Django 4.2.27 on 2025-12-19 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_sitesetting_place_order_summary_background_color_and_more'),
        ('core', '0037_sitesetting_subscription_subtitle_and_more'),
    ]

    operations = [
    ]
