# Generated by Django 4.2.27 on 2025-12-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_merge_20251219_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSetting',
            fields=[
            ],
            options={
                'verbose_name': 'Payment Configuration',
                'verbose_name_plural': 'Payment Configuration',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesetting',),
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='place_order_summary_background_color',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='place_order_summary_border_color',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='place_order_summary_text_color',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='place_order_summary_title_color',
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='payment_api_key',
            field=models.CharField(blank=True, help_text='Your Secret Key or API Key.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='payment_category_code',
            field=models.CharField(blank=True, help_text='Required for ToyyibPay (Category Code) or Billplz (Collection ID).', max_length=100, verbose_name='Category Code / Collection ID'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='payment_enabled',
            field=models.BooleanField(default=False, help_text='Enable or disable online payments globally.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='payment_gateway_url',
            field=models.CharField(default='https://dev.toyyibpay.com/index.php/api/createBill', help_text='The API Endpoint URL (e.g., https://toyyibpay.com/index.php/api/createBill).', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='payment_provider',
            field=models.CharField(choices=[('TOYYIBPAY', 'ToyyibPay (FPX/Malaysia)'), ('BILLPLZ', 'Billplz (FPX/Malaysia)'), ('STRIPE', 'Stripe (Credit Card)')], default='TOYYIBPAY', help_text='Select the logic handler for processing payments.', max_length=20),
        ),
    ]
